name: Deploy App

on: [push]

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore Terraform
        id: cache
        uses: actions/cache@v4
        with:
          path: ci/cache/docker/terraform
          key: ${{ hashFiles('./infra/Dockerfile') }}

      - name: Build Terraform
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          docker build -t terraform infra/
          mkdir -p ci/cache/docker/terraform
          docker image save terraform --output ./ci/cache/docker/terraform/image.tar

      - name: Terraform Apply
        run: |
          docker image load -q --input ./ci/cache/docker/terraform/image.tar

          for cmd in init apply; do
            docker run --rm --entrypoint terraform \
              -w /tmp/terraform \
              -v $PWD/infra:/tmp/terraform \
              -e TF_CLI_ARGS_init=-backend-config="bucket=${{ secrets.TF_BACKEND_BUCKET }}" \
              -e TF_CLI_ARGS_apply=-auto-approve \
              -e AWS_REGION=us-west-2 \
              -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
              -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
              -e TF_VAR_github_token=${{ secrets.GH_TOKEN }} \
              terraform $cmd
          done
